"""empty message

Revision ID: 90246b83f72b
Revises: c896851ebb7a
Create Date: 2026-02-22 17:43:03.538089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90246b83f72b'
down_revision = 'c896851ebb7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_memos_users', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_memos_users', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
